[build]
  command = "npm run build"
  publish = ".next"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/api/auth/callback"
  to = "https://mest.netlify.app"
  status = 200
[[plugins]]
  package = "@netlify/plugin-nextjs"